### PR TITLE
Enhancments 1.21.2

### PR DESCRIPTION
**Pull request by lscheffler**
#### Enhancement:
- inserted option UseFilesPerDBC to split DBC processing from vcx / scx
- inserted option RedirectFilePerDBCToMain to split DBC processing from vcx / scx
- inserted option ItemPerDBCCheck to split DBC processing from vcx / scx
- the three above are straight forward, so no extra comment are within the code
- inserted option DBF_BinChar_Base64 to allow processing of NoCPTrans fields in non base64 way
- inserted option DBF_IncludeDeleted to allow including deleted records of DBF
- German translation improved
- Info screen-doc improved
- added option to create config file template
- inserted option OldFilesPerDBC to define the use splitting of DBC like version pre 1.21.0

#### Fixes
- DBF_Conversion_Condition, problem with macro expansion

### CODE REVIEW

**Review by DougHennig — APPROVED** [review]

**Comment by fdbozzo** [comment]
Hi @DougHennig ,

Ok, I've been able to do it.I tell you how I did it:

The GitHub instructions says to follow this steps, on which I did add the automatic resolution of conflicts taking "theirs":

git fetch
git checkout master
git pull
git checkout -b lscheffler-fork_mod master
git pull -s recursive -X theirs --no-ff https://github.com/lscheffler/foxbin2prg.git fork_mod
git checkout master
git merge --no-ff lscheffler-fork_mod
git push origin master

@lscheffler, I copy here something that already explained to Doug few days ago and that you should know:

Have in mind that changing the main version "n_FB2PRG_Version = 1.19" to something else (i.e."1.21"), will cause that from now, every TX2 file will be generated with this version in the header, that actually shows as this:

*< FOXBIN2PRG: Version=**"1.19"** SourceFile="fb2p_diff.pjx" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries) 

The above line will change to this:
*< FOXBIN2PRG: Version=**"1.21"** SourceFile="fb2p_diff.pjx" /> (Solo para binarios VFP 9 / Only for VFP 9 binaries) 

So even without any changes in the code, all files of the project will be regenerated as modified for those that update FoxBin2Prg. 
That's why I didn't change it in the past and why I did keep only iterating over version 1.19.XX

Just wanted to let you know.

Take care of the user base, that will complain with this type of change.

Best regards.-

**Comment by DougHennig** [comment]
@fdbozzo I tried those steps but got the error I mentioned on the last command (git push origin master). It looks like I cannot push directly to the repository so I will have to use pull requests. The only problem with that is GitHub will not allow me to review my own pull requests, so when I make changes, you will have to review the pull requests before they can be merged.

@lscheffler I agree with @fdbozzo: I had changed the version to 1.20 but think it should go back to 1.19.XX.

**Comment by lscheffler** [comment]
@fdbozzo   
Yeah, I remember this now.   
Didn't happen to me, so I didn't notice. I use my https://github.com/lscheffler/bin2text - and partially purpose of that is to generate only those text files where the binary (down to class level) has changed. So, it simply runs, but creates the Text only if the binary is changed anyway. 
@DougHennig    
But for the general audience it might be better. Should I push to the fork?

**Comment by DougHennig** [comment]
@lscheffler Yes, I think you should change the version to something like 1.19.55 and do another pull request.

**Comment by fdbozzo** [comment]
@DougHennig <https://github.com/DougHennig>
I think that then, the solution can be the creation of a repository key I
proposed, which apparently gives you the possibility to merge directly
using it.

**Comment by DougHennig** [comment]
@fdbozzo OK, that would make things easier.

**Comment by fdbozzo** [comment]
Ok, I will write you on private.

**Pull request merged**
