### PR TITLE
Added support for BodyDevInfo = 2 in CFG file

### PR DESCRIPTION
**Pull request by DougHennig**
v1.21.04: Added support for BodyDevInfo = 2 in CFG file to prevent both DevInfo and ObjRev from being written to PJ2 file

### CODE REVIEW

**Comment by lscheffler** [comment]
Hi @DougHennig,

Great!

I  have no idea what those two fields are good for. So I trust that it makes sense to clean them together and that there is no need to clean _ObjRev_ only. Otherwise I would recommend a single (On/Off) setting  special for _ObjRev_.

According to [CONTRIBUTING](https://github.com/DougHennig/foxbin2prg/blob/master/.github/CONTRIBUTING.md), would you mind to alter, :
- Version number on top of Create_FoxBin2Prg.cfg (I need to update this in the contrib file)
- README.md
- docs\ChangeLog.md
- docs\FoxBin2Prg_Internals.md
   -  the table at _Configuration file_ is missing `BodyDevInfo` at all. Would you be so kind to add it, and give a little hint what it is good for? It should be enough inside this table.

Thank you!

**Comment by DougHennig** [comment]
@lscheffler Done.

**Comment by lscheffler** [comment]
So far. Except, when you follow https://github.com/fdbozzo/foxbin2prg/pull/109/commits/8384b6c100e0c14f76b3ba83195d43b9c3b7dc8f ; 

grafik

this is the diff you see above as, you see that all the md files are changed as a whole. Your editor has altered CRLF to LF. Please use something that keeps the line endings. (My guess: not the github UI,  it does not look like your git is the culprit, since the prg is fine)

**Comment by lscheffler** [comment]
@Doug I can do this, but not via the GH interface, because this would force me to merge to master branch, and then the change is published. I would get your change to my local repo, alter, merge and push in my name. This means, your visible contribution is lost to GH, but still valid in FoxBin2Prg and it's git history.

**Comment by DougHennig** [comment]
I used Markdown Monster, which was configured for LF. I've changed that to CRLF and updated the MD files.

**Comment by lscheffler** [comment]
I know I'm a pain. But contribution, New version:

> 12. Please alter the footer of *.md files touched to recent date.

##### off topic
Is markdown able to just keep line endings? If not, one should talk to Rick ...

**Comment by DougHennig** [comment]
Sorry, I missed that. Done.

According to the docs, Markdown Monster is supposed to keep existing line endings but appears to change them to the selected ones. I have it configured to use CRLF now.

**Pull request merged**
